name: Python build and tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  create:
    branches: [master]
    tags: ['**']
  schedule:
    - cron: "0 4 1 * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.6

    - name: Update pip, setuptools, and wheel
      run: python -m pip install --upgrade pip setuptools wheel

    - uses: actions/checkout@v2
    - name: Build sdist
      run: python setup.py sdist
    - name: Install sdist
      run: pip install ./dist/eeg_positions-*
    - name: Clean up working directory
      run: rm -rf ./*
    - name: Try importing eeg_positions
      run: python -c 'import eeg_positions; print(eeg_positions.__version__)'
    - name: Remove sdist install
      run: pip uninstall -y eeg_positions

    - uses: actions/checkout@v2
    - name: Build wheel
      run: python setup.py bdist_wheel
    - name: Install wheel
      run: pip install ./dist/eeg_positions-*.whl
    - name: Clean up working directory
      run: rm -rf ./*
    - name: Try importing eeg_positions
      run: python -c 'import eeg_positions; print(eeg_positions.__version__)'
    - name: Remove wheel install
      run: pip uninstall -y eeg_positions

  test:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        make inplace

    - name: Check formatting
      if: "matrix.platform == 'ubuntu-latest'"
      run: |
        make flake
        make check-manifest

    - name: Test with pytest
      run: |
        make test

    - name: Upload coverage report
      if: "matrix.platform == 'ubuntu-latest'"
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
